### ISSUE TITLE
Can I have write access to this repository?

### ISSUE THREAD

**Issue by WaxyMocha** [WoeUSB/WoeUSB-ng#1]
## Good Habit Checklist for Issue Reporting
Checkout [Mastering Markdown · GitHub Guides](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) if you needs help on the GitHub-flavored Markdown syntax.  You may remove sections and contents that don't apply.

* [x] I've searched the issue tracker and is pretty sure that there's no duplicate issue already filed
* [ ] I've built the latest development snapshot using the instructions in README and verified that the issue can still be reproduced (for bug reports)

## Expected Behavior
> Write access :smile: 

## Current Behavior
> ERROR: Permission to WoeUSB/WoeUSB-ng.git denied to WaxyMocha.

**Comment by WaxyMocha** [comment]
@Lin-Buo-Ren

**Comment by Lin-Buo-Ren** [comment]
I've adjusted the default permission of all members to have write access to all the repoes, have fun!
