### ISSUE TITLE
install fails after installing dependencies

### ISSUE THREAD

**Issue by tescophil** [WoeUSB/WoeUSB-ng#10]
## Good Habit Checklist for Issue Reporting
Checkout [Mastering Markdown · GitHub Guides](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) if you needs help on the GitHub-flavored Markdown syntax.  You may remove sections and contents that don't apply.

* [x ] I've searched the issue tracker and is pretty sure that there's no duplicate issue already filed
* [ ] I've built the latest development snapshot using the instructions in README and verified that the issue can still be reproduced (for bug reports)

## Issue Reproduce Instructions
Installed dependencies, then attempted the second install step which failed
```
phil@Desktop-PC:~$ sudo pip3 install WoeUSB-ng
Collecting WoeUSB-ng
  Downloading https://files.pythonhosted.org/packages/a4/7d/2872b53d9d713f0a3eb5952ad3df8e2bf23184baa2e00fe803830852e884/WoeUSB-ng-0.2.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-1len5mx7/WoeUSB-ng/setup.py
```    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-1len5mx7/WoeUSB-ng/
phil@Desktop-PC:~$ `

## Expected Behavior
Install succeeds

## Current Behavior
Install Fails

### WoeUSB Version
N/A

### WoeUSB Source
Followed the readme

### Information about the Operating System
Debian 10

### Information about the Source Media
N/A

### Information about the Target Device
N/A

**Comment by WaxyMocha** [comment]
Oh no, why it is trying to download yanked release from pypi

**Comment by WaxyMocha** [comment]
Please continue in #11
