### ISSUE TITLE
Broken Project

### ISSUE THREAD

**Issue by LightYagami28** [WoeUSB/WoeUSB-ng#114]
@WoeUSB this is a project dead? Why you don't update? Or fix the @issues?

**Comment by brlin-tw** [comment]
No, the projects are not dead, it is just that the maintainers are out of capacity at the moment.  Please understand that people have their priorities that may hinder the projects' development.

If you have problems with a specific issue(s) regarding WoeUSB/WoeUSB-ng, please highlight them using GitHub's reaction feature, thanks!
