### ISSUE TITLE
SkiddroNG (Placeholder title) - An updated and cross-platform version of WoeUSB-NG

### ISSUE THREAD

**Issue by ghost** [WoeUSB/WoeUSB-ng#126]
This is pretty much just to show what I'm doing for WoeUSB-NG instead of an issue.
SkiddroNG is my own version of WoeUSB-NG, designed to be optimized and updated for better performance, more features, and to be for both Windows and Linux. The image given is a prototype version of the Windows version of SkiddroNG.
![image](https://github.com/user-attachments/assets/b3950f02-90c3-40bc-80cf-52fd70df7de1)

What I'm planning to do for more features is add the ability to do stuff such as remove the TPM, RAM, etc checks for Windows 11's installer, enable and auto-login to the Administrator user account, create a persistent storage partition for Debian-based and Ubuntu-based distros (Linux-version only), and a few other stuff.

Why I'm doing this meanwhile Rufus exists? Well, it's just for fun, lol. Anyways, that's all for now. I will upload my source code and stuff of SkiddroNG soon in the future.

**Comment by brlin-tw** [comment]
Hello, while I personally welcome alternative implementations of WoeUSB(-ng), this is not the proper place to place their promotional information.

Feel free to add an entry to [the Alternatives page of the WoeUSB wiki](https://github.com/WoeUSB/WoeUSB/wiki/Alternatives), thank you.
