### ISSUE TITLE
<urlopen error [Errno -2] Name or service not known>

### ISSUE THREAD

**Issue by Xphobia** [WoeUSB/WoeUSB-ng#14]
### Problem

woeusb command failed with errors "<urlopen error [Errno -2] Name or service not known>"

### Test Environment
(1) OS: CentOS Linux release 7.6.1810 (Core), it's a vmware guest, say, centos76-vm.
(2) WoeUSB-ng: 0.2.6

### How to reproduce
(1) Add scsi disk (/dev/sdb) to centos76-vm
(2) excute woeusb command as follows
```
woeusb --tgt-fs NTFS -d en_windows_server_2012_vl_x64_dvd_917758.iso /dev/sdb
```

### Expected
build successfully

### Actual
build failed

## More infomation
![woeusb-ng](https://user-images.githubusercontent.com/59901623/104890080-03eb5980-59aa-11eb-92e1-e6c922e30393.jpg)

**Comment by WaxyMocha** [comment]
At one of the last stages of creating a bootable pendrive, woeusb downloads uefi image from github, maybe you were not connected to internet? Can you open [https://github.com/pbatard/rufus/raw/master/res/uefi/](https://github.com/pbatard/rufus/raw/master/res/uefi/)?

**Comment by Xphobia** [comment]
> At one of the last stages of creating a bootable pendrive, woeusb downloads uefi image from github, maybe you were not connected to internet? Can you open https://github.com/pbatard/rufus/raw/master/res/uefi/?

Thanks. Yes, it's the network problem.

**Comment by WaxyMocha** [comment]
I'll fix error catch so the error will be more verbose.
