### ISSUE TITLE
[Errno 2] No such file or directory: 'grub-install': 'grub-install'

### ISSUE THREAD

**Issue by Xphobia** [WoeUSB/WoeUSB-ng#15]
## Issue Reproduce Instructions
> 1. Launch WoeUSB by running command
```
woeusb --verbose  --tgt-fs NTFS --device en_windows_server_2012_vl_x64_dvd_917758.iso /dev/sdb
```
> 2. Output with errors
![woeusb-debug2](https://user-images.githubusercontent.com/59901623/105028503-14740080-5a8c-11eb-9ab4-ea4546cbe225.jpg)

## Expected Behavior
> No error

## Current Behavior
> WoeUSB errors with message "[Errno 2] No such file or directory: 'grub-install': 'grub-install'"

### WoeUSB Version
> v0.2.6

### WoeUSB Source
> Built from source code, v0.2.6

### Information about the Operating System
>  Tested in Vmware guest, CentOS Linux release 7.6.1810 (Core)

### Information about the Source Media
> en_windows_server_2012_vl_x64_dvd_917758.iso

### Information about the Target Device
> A Vmware scsi disk

### Debugging
In the test environment(Centos7.6), there is no command named 'grub-install', 'grub2-install' exists.
I go through the source code and find where it happens. It happened in function 'check_runtime_dependencies' in file WoeUSB/utils.py, where called shutil.which() to judge which command to use. 
![woeusb-bug](https://user-images.githubusercontent.com/59901623/105016480-a6c0d800-5a7d-11eb-989e-bf7903f945a8.jpg)

It's the if clause matter. when a command, say, 'grub-install' does not exists, shutil.which() returns None instead of ''.
I tested shutil.which() in python3 interpreter.
![woeusb-debug](https://user-images.githubusercontent.com/59901623/105017243-85acb700-5a7e-11eb-9106-5dca3cec30ec.jpg)

It's a convention to write such kind of if clause as follows

    ·```
    grub = ["grub-install", "grub2-install"]
    for command in grub:
        if shutil.which(command):
            grub = command
            break
    ```
or

    ·```
    grub = ["grub-install", "grub2-install"]
    for command in grub:
        if shutil.which(command) is not None:
            grub = command
            break
    ```

**Comment by WaxyMocha** [comment]
Hi, sorry for that delay in response, also thank you for providing solution! I will test it and push the fix.

**Comment by RUvlad1** [comment]
I'm having the same problem, I'm on Pop!_OS using the GUI option
![image](https://user-images.githubusercontent.com/60317461/109392206-e9eb5200-792b-11eb-9559-81b3a882d8a4.png)

**Comment by Xphobia** [comment]
> I'm having the same problem, I'm on Pop!_OS using the GUI option
It's fixed in the latest version. what's your  version ?

**Comment by WaxyMocha** [comment]
I don't think that this is an issue here, from quick googling it turns out that pop doesn't use grub so it makes sense that it will be missing. @RUvlad1 Can you try to install grub package and try again? If it would work, can you post what package it was?

**Comment by therealaleph** [comment]
> I'm having the same problem, I'm on Pop!_OS using the GUI option
> ![image](https://user-images.githubusercontent.com/60317461/109392206-e9eb5200-792b-11eb-9559-81b3a882d8a4.png)

`sudo apt-get install grub2-common
`
