### ISSUE TITLE
[Errno 13] Permission denied: '/dev/sda2'

### ISSUE THREAD

**Issue by InfRandomness** [WoeUSB/WoeUSB-ng#17]
## Good Habit Checklist for Issue Reporting
Checkout [Mastering Markdown · GitHub Guides](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) if you needs help on the GitHub-flavored Markdown syntax.  You may remove sections and contents that don't apply.

* [ ] I've searched the issue tracker and is pretty sure that there's no duplicate issue already filed
* [x] I've built the latest development snapshot using the instructions in README and verified that the issue can still be reproduced (for bug reports)

## Issue Reproduce Instructions
> 1. Launch WoeUSB with the gnome launcher menu
> 2. Insert an USB or an external hard drive or an internal hard drive
> 3. Try to write a windows 10 ISO

## Expected Behavior
> Having the ISO written on the drive

## Current Behavior
> WoeUSB errors with message 
```
[Errno 13] Permission denied: '/dev/sdX2'
```

### WoeUSB Version
tested on :
 v0.2.5
v0.2.5-18-g445789d

### Information about the Operating System
```
NAME=Fedora
VERSION="33 (Workstation Edition)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora 33 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f33/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=33
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=33
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

### Information about the Source Media
> Windows 10 English

### Information about the Target Device
> Sandisk 16 gb USB Key
> Two Hard drives : one seagate and one toshiba.

**Comment by WaxyMocha** [comment]
At this moment I really can only tell you to use terminal, sorry.
`sudo woeusb`

**Comment by InfRandomness** [comment]
I used sudo for the operation

**Comment by InfRandomness** [comment]
regular woeusb was so much better, eww woeusb-ng.

**Comment by vectorcr** [comment]
I am running into this same problem on Fedora 34. 

`==============================
Mounting source filesystem...
Wiping all existing partition table and filesystem signatures in /dev/sda
/dev/sda: 2 bytes were erased at offset 0x000001fe (dos): 55 aa
/dev/sda: calling ioctl to re-read partition table: Success
Ensure that /dev/sda is really wiped...
Creating new partition table on /dev/sda...
Creating target partition...
Making system realize that partition table has changed...
Wait 3 seconds for block device nodes to populate...
Cluster size has been automatically set to 4096 bytes.
Creating NTFS volume structures.
mkntfs completed successfully. Have a nice day.
[Errno 13] Permission denied: '/dev/sda2'
Unmounting and removing /media/woeusb_source_1627171747_41815...
You may now safely detach the target device
`

**Comment by vectorcr** [comment]
Never mind! The iso I was using did not need to be NTFS because I was using the LTSC variant of windows. Hence running `sudo woeusb --device LTSCX64.ENU.MAY2021.iso /dev/sda` fixed my issue. I just removed the `--target-filesystem NTFS argument`

**Comment by ergpopler** [comment]
F***, someone fix this. Why was this issue closed? Can it be reopened?

**Comment by jelabarre59** [comment]
Same problem, Fedora36.  Ran it with sudo.

Even zeroed out the partition table then tried again.   Continues to fail with a permissions error on sdX2 even though I have run it under sudo.

Where is the OLD version that actually worked?

**Comment by darkpiv** [comment]
you guys need to allow python3 access the /dev...

```
sudo ausearch -c 'python3' --raw | audit2allow -M my-python3
sudo semodule -X 300 -i my-python3.pp
```

**Comment by MasterCruelty** [comment]
Fedora 36, same problem.
Can someone open again this issue?

**Comment by hcal** [comment]
I think this is a selinux issue on Fedora.  
I turned it off (temp) by running the command below and it seems to have worked.
`setenforce 0`

**Comment by jelabarre59** [comment]
Oh yes, fix a bad programme by disabling security for the ENTIRE system.  That will end well...

**Comment by hcal** [comment]
> Oh yes, fix a bad programme by disabling security for the ENTIRE system. That will end well...

I was trying to add some useful information to the bug report but yes, please don't do this.

**Comment by frdsndr** [comment]
> I think this is a selinux issue on Fedora. I turned it off (temp) by running the command below and it seems to have worked. `setenforce 0`

Yes thanks! This works.

```sh
# get status of SELinux
sestatus
# check enforcing
getenforce
# disable temporarily
sudo setenforce 0 # a reboot reverts the setting
# run woeusb

# re-enable enforcing:
sudo setenforce 1
getenforce # verify

```

**Comment by rishikesh2003** [comment]
> @jelabarre59 you guys need to allow python3 access the /dev...
> 
> ```
> sudo ausearch -c 'python3' --raw | audit2allow -M my-python3
> sudo semodule -X 300 -i my-python3.pp
> ```

This fixed my issue
Fedora 38

**Comment by mon-jai** [comment]
@darkpiv's solution worked for me.

Thanks for saving my day.

**Comment by kookyleo** [comment]
> @jelabarre59 you guys need to allow python3 access the /dev...
> 
> ```
> sudo ausearch -c 'python3' --raw | audit2allow -M my-python3
> sudo semodule -X 300 -i my-python3.pp
> ```

This fixed my issue too, Fedora  38
& Add a cleanup action —
```
sudo semodule -X 300 -r my-python3
```
