### ISSUE TITLE
WoeUSB-ng leaves the USB empty, or even the ntfs filesystem corrupt

### ISSUE THREAD

**Issue by Snivyer1910** [WoeUSB/WoeUSB-ng#18]
Hi, I'm trying to create a Windows 10 USB with WoeUSB using the latest 20H2, the installation "succeeds" but there's nothing on the flash and it doesn't appear on the boot menu, or sometimes you can't even mount the filesystem again, WoeUSB is definitely doing something to the USB since it heats up when WoeUSB is "copying" the files (normal behavior of flash drives to heatup when in use btw) if you need any screenshot/photos or logs I can provide you with them

OS: Xubuntu 20.10
WoeUSB version: Compiled from Github
Windows 10 ISO: Spanish (Mexico) 20H2

**Extra Notes:**

using gparted to manually format the flash drive to ntfs gives errors, using gnome disk utility also gives errors, It might be something wrong with my OS not being able to correctly handle ntfs filesystems, but I don't know how I can fix that :P

**Comment by JonnyTech** [comment]
> using gparted to manually format the flash drive to ntfs gives errors, using gnome disk utility also gives errors

Your USB drive os faulty. Probably due to overheating while writing the extracted ISO to it. Cheap drives do fail like that very often. Throw it away and get a better drive.

**Comment by Snivyer1910** [comment]
that can't be the issue because I can create filesystems from other types but ntfs, and transfer files to it, heck I even used that same flash drive to install Xubuntu, and even windows but since I only have one bc I lost my other flash drive that's the best I can do :P

**Comment by JonnyTech** [comment]
Zero the drive: `sudo dd if=/dev/zero of=/dev/sdX` (replace sdX with your drive identifier)

Then rerun `woeusb` and copy/paste all terminal output here, including your command input, so we can see what is happening.

**Comment by Snivyer1910** [comment]
nevermind my USB drive is indeed faulty, but I have no extra USB Drives so I guess I'm suck :P
