### ISSUE TITLE
How do I use this? 

### ISSUE THREAD

**Issue by dhiegomaga** [WoeUSB/WoeUSB-ng#19]
There are no instructions on how to execute, how do you execute this? 

Thanks in advance.

**Comment by WaxyMocha** [comment]
Hi! After instalation (https://github.com/WoeUSB/WoeUSB-ng#installation), you should have shortcut in your apps (press Windows key and type woeusb), if this won't work you can open terminal and use `woeusbgui` command. If this still won't work, use `sudo woeusb`.
