### ISSUE TITLE
Pip package cannot be installed locally

### ISSUE THREAD

**Issue by ElSaico** [WoeUSB/WoeUSB-ng#2]
## Good Habit Checklist for Issue Reporting

* [x] I've searched the issue tracker and is pretty sure that there's no duplicate issue already filed
* [x] I've built the latest development snapshot using the instructions in README and verified that the issue can still be reproduced (for bug reports)

## Issue Reproduce Instructions
> Run `pip install woeusb-ng` under a local environment (pyenv, virtualenv)

## Expected Behavior
> The package gets installed successfully and creates executables under the appropriate `bin/` folder

## Current Behavior
>  error: [Errno 13] Permission denied: '/usr/local/bin/woeusbgui'

### WoeUSB Version
> 0.2.0

### Information about the Operating System
> Manjaro Linux

**Comment by aasril** [comment]
same issue with `--user` install option( `pip install --user WoeUSB-ng`).

**Comment by WaxyMocha** [comment]
I'm working on it. If anyone knows how to get bin directory that will be used by pip, please let me know.

**Comment by WaxyMocha** [comment]
So I'm back at the point where I believe that it is impossible to do this with pip, I can't get my hands on path to `bin` that will be used by pip and I need that path do create policy (required for running GUI as root) and shortcut in menu (for user convenience). 
I added code that allows woeusbgui to detect that something is wrong with policy and fix it but this is not a full fix for my problem.
So for now, the `woeusbgui` script is hard-coded to be copied to `/usr/local/bin`, if you want to install it locally or in virtual environment you need to add `woeusbgui` script to `scripts` in setup.py, you can do this using this patch:
```
diff --git a/setup.py b/setup.py
index dca8421..b3e02fe 100644
--- a/setup.py
+++ b/setup.py
@@ -72,6 +72,7 @@ setup(
     include_package_data=True,
     scripts=[
         'WoeUSB/woeusb',
+        'WoeUSB/woeusbgui',
     ],
     install_requires=[
         'termcolor',
```
and then installing with `-e` parameter, e.g.:
```
pip3 install -e .
```
While being in WoeUSB-ng directory obviously. 

This way `woeusbgui` script will be copied by pip to correct place and using `-e` switch will skip creation of menu shortcut, please note that you may need to run program twice, as on first time WoeUSB may adjust the policy.

**Comment by RealJTG** [comment]
> I can't get my hands on path to `bin` that will be used by pip and I need that path do create policy (required for running GUI as root)

`sys.prefix` or `sys.exec_prefix` I guess? 
https://docs.python.org/3/library/sys.html#sys.prefix
https://docs.python.org/3/library/sys.html#sys.exec_prefix

```
> cd /tmp
> python -c 'import os, sys;print(os.path.join(sys.prefix, "bin"))'
/usr/bin

> python -m venv venv
> . venv/bin/activate
(venv) > python -c 'import os, sys;print(os.path.join(sys.prefix, "bin"))'
/tmp/venv/bin
```

**Comment by WaxyMocha** [comment]
:open_mouth: Thank you!

**Comment by edcdecl** [comment]
five years later, how are you supposed to do this? there is no kwarg "scripts" passed to setup
