### ISSUE TITLE
Translations welcome?

### ISSUE THREAD

**Issue by Etamuk** [WoeUSB/WoeUSB-ng#22]
Hello,

no, no issue. It´s just a question :-)
Today I created a bootable Windows 10 image using WoeUSB-ng to repair my sisters notebook.
I am really happy that I found this tool to help me.
After that I noticed there is no german translation. 
So I toke that pot file and did some work on it.
I will upload it here to this project, alright? 

Kind regards from Germany

**Comment by WaxyMocha** [comment]
I see no problem with this, I'll happily accept translations :smile:.

**Comment by Etamuk** [comment]
Thanks. 
Done :checkered_flag:
