### ISSUE TITLE
Media coverage

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [WoeUSB/WoeUSB-ng#28]
[Use this bootable USB drive on Linux to rescue Windows users | Opensource.com](https://opensource.com/article/21/2/linux-woeusb)

Cheers!

**Comment by WaxyMocha** [comment]
😮

**Comment by WaxyMocha** [comment]
its a bit funny that they didn't mentioned dependencies, I'm sure that using just pip will fail😆

**Comment by WaxyMocha** [comment]
Also: http://support.system76.com/articles/dual-booting/#creating-install-media

**Comment by WaxyMocha** [comment]
In Insights tab under Traffic you can see some sources of traffic
