### ISSUE TITLE
woeusb-ng hangs on 'install-grub' step

### ISSUE THREAD

**Issue by zhenpingfeng** [WoeUSB/WoeUSB-ng#32]
same as https://github.com/slacka/WoeUSB/issues/251
this version is 'ng' but still has this bug?

**Comment by Lin-Buo-Ren** [comment]
It is your drive's poor I/O performance that causes the issue, not WoeUSB/WoeUSB-ng.

We are working on a solution that will eliminate most of the aforementioned use case, however the root cause is still not at our end anyway.

**Comment by zhenpingfeng** [comment]
Ok, despite the long waiting time, the creation was finally completed

**Comment by ParthMandaliya** [comment]
The problem is still there.
It running for an hour, I doubt if it'll finish successfully.

**Comment by ParthMandaliya** [comment]
Finally it did finish successfully

**Comment by PattMayne** [comment]
It took two full hours for me but it finally finished, and seems to have been successful. Patience is a virtue.

**Comment by a9udn9u** [comment]
Is there a plan to improve this?
I understand it's caused by poor I/O performance (using a USB 2.0 drive) but 2 hours for installing bootloader seems absurd.

**Comment by Seneral** [comment]
I think this would be easily improved by flushing after/during the writing step so it's clear to the user it's still writing, and it's not hanging unreasonably on a seemingly quick step like installing a bootloader. Made me abort and discard woeusb before (woeusb-ng happens to not work at all for me, besides the point)
