### ISSUE TITLE
Wild unmounting spree attempt on unmet dependency?

### ISSUE THREAD

**Issue by ITikhonov** [WoeUSB/WoeUSB-ng#37]
I am pretty sure that's not what should be happening:

x@ubuntu:~/WoeUSB-ng$ sudo env PYTHONPATH=. WoeUSB/woeusb --device /dev/sr0 /dev/sdd
Error: WoeUSB requires 7z command in the executable search path, but it is not found.
Dependencies are not met
Warning: The following partitions will be unmounted: ['sysfs', '', 'on', '', '/sys', '', 'type', '', 'sysfs', '', '(rw,nosuid,nodev,noexec,relatime)', '', 'proc', '', 'on', '', '/proc', '', 'type', '', 'proc', '', '(rw,nosuid,nodev,noexec,relatime)', '', 'udev', '', 'on', '', '/dev', '', 'type', '', 'devtmpfs', '', '(rw,nosuid,relatime,size=214892k,nr_inodes=53723,mode=755)', '', 'devpts', '', 'on', '', '/dev/pts', '', 'type', '', 'devpts', '', '(rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)', '', 'tmpfs', '', 'on', '', '/run', '', 'type', '', 'tmpfs', '', '(rw,nosuid,noexec,relatime,size=49272k,mode=755)', '', '/dev/sda2', '', 'on', '', '/', '', 'type', '', 'ext4', '', '(rw,relatime,data=ordered)', '', 'securityfs', '', 'on', '', '/sys/kernel/security', '', 'type', '', 'securityfs', '', '(rw,nosuid,nodev,noexec,relatime)', '', 'tmpfs', '', 'on', '', '/dev/shm', '', 'type', '', 'tmpfs', '', '(rw,nosuid,nodev)', '', 'tmpfs', '', 'on', '', '/run/lock', '', 'type', '', 'tmpfs', '', '(rw,nosuid,nodev,noexec,relatime,size=5120k)', '', 'tmpfs', '', 'on', '', '/sys/fs/cgroup', '', 'type', '', 'tmpfs', '', '(ro,nosuid,nodev,noexec,mode=755)', '', 'cgroup', '', 'on', '', '/sys/fs/cgroup/unified', '', 'type', '', 'cgroup2', '', '(rw,nosuid,nodev,noexec,relatime)', '', 'cgroup', '', 'on', '', '/sys/fs/cgroup/systemd', '', 'type', '', 'cgroup', '', '(rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)', '', 'pstore', '', 'on', '', '/sys/fs/pstore', '', 'type', '', 'pstore', '', '(rw,nosuid,nodev,noexec,relatime)', '', 'cgroup', '', 'on', '', '/sys/fs/cgroup/memory', '', 'type', '', 'cgroup', '', '(rw,nosuid,nodev,noexec,relatime,memory)', '', 'cgroup', '', 'on', '', '/sys/fs/cgroup/rdma', '', 'type', '', 'cgroup', '', '(rw,nosuid,nodev,noexec,relatime,rdma)', '', 'cgroup', '', 'on', '', '/sys/fs/cgroup/hugetlb', '', 'type', '', 'cgroup', '', '(rw,nosuid,nodev,noexec,relatime,hugetlb)', '', 'cgroup', '', 'on', '', '/sys/fs/cgroup/net_cls,net_prio', '', 'type', '', 'cgroup', '', '(rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)', '', 'cgroup', '', 'on', '', '/sys/fs/cgroup/perf_event', '', 'type', '', 'cgroup', '', '(rw,nosuid,nodev,noexec,relatime,perf_event)', '', 'cgroup', '', 'on', '', '/sys/fs/cgroup/cpu,cpuacct', '', 'type', '', 'cgroup', '', '(rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)', '', 'cgroup', '', 'on', '', '/sys/fs/cgroup/blkio', '', 'type', '', 'cgroup', '', '(rw,nosuid,nodev,noexec,relatime,blkio)', '', 'cgroup', '', 'on', '', '/sys/fs/cgroup/freezer', '', 'type', '', 'cgroup', '', '(rw,nosuid,nodev,noexec,relatime,freezer)', '', 'cgroup', '', 'on', '', '/sys/fs/cgroup/cpuset', '', 'type', '', 'cgroup', '', '(rw,nosuid,nodev,noexec,relatime,cpuset)', '', 'cgroup', '', 'on', '', '/sys/fs/cgroup/devices', '', 'type', '', 'cgroup', '', '(rw,nosuid,nodev,noexec,relatime,devices)', '', 'cgroup', '', 'on', '', '/sys/fs/cgroup/pids', '', 'type', '', 'cgroup', '', '(rw,nosuid,nodev,noexec,relatime,pids)', '', 'systemd-1', '', 'on', '', '/proc/sys/fs/binfmt_misc', '', 'type', '', 'autofs', '', '(rw,relatime,fd=25,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=13566)', '', 'mqueue', '', 'on', '', '/dev/mqueue', '', 'type', '', 'mqueue', '', '(rw,relatime)', '', 'hugetlbfs', '', 'on', '', '/dev/hugepages', '', 'type', '', 'hugetlbfs', '', '(rw,relatime,pagesize=2M)', '', 'debugfs', '', 'on', '', '/sys/kernel/debug', '', 'type', '', 'debugfs', '', '(rw,relatime)', '', 'configfs', '', 'on', '', '/sys/kernel/config', '', 'type', '', 'configfs', '', '(rw,relatime)', '', 'fusectl', '', 'on', '', '/sys/fs/fuse/connections', '', 'type', '', 'fusectl', '', '(rw,relatime)', '', 'shared', '', 'on', '', '/media/vbox', '', 'type', '', 'vboxsf', '', '(rw,nodev,relatime)', '', 'lxcfs', '', 'on', '', '/var/lib/lxcfs', '', 'type', '', 'fuse.lxcfs', '', '(rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)', '', '/var/lib/snapd/snaps/core_10444.snap', '', 'on', '', '/snap/core/10444', '', 'type', '', 'squashfs', '', '(ro,nodev,relatime,x-gdu.hide)', '', '/var/lib/snapd/snaps/core_10577.snap', '', 'on', '', '/snap/core/10577', '', 'type', '', 'squashfs', '', '(ro,nodev,relatime,x-gdu.hide)', '', 'tmpfs', '', 'on', '', '/run/user/1000', '', 'type', '', 'tmpfs', '', '(rw,nosuid,nodev,relatime,size=49268k,mode=700,uid=1000,gid=1000)', '']
umount: /sys: target is busy.
Target device is busy, please make sure you unmount all filesystems on target device or shutdown the computer before detaching it.

**Comment by WaxyMocha** [comment]
Oh God.

So this was apparently introduced in #24, when woeusb-ng fails it throws exception which is caught and cleanup() is called, it in turn calls utils.check_is_target_device_busy() which before #24 was just returning error when there were mounted drives, but now I see the error, cleanup() is using global variable that is apparently never set.

I'll revert v0.2.8 as it is dangerous to use, and I don't have time on hand to fix it.

**Comment by ITikhonov** [comment]
Thanks! Luckily, `sys` will be the first most of the time and it is a pretty tough one to unmount.
