### ISSUE TITLE
linux_make_writeback_buffering_not_suck() throws exception 

### ISSUE THREAD

**Issue by WaxyMocha** [WoeUSB/WoeUSB-ng#4]
When `linux_make_writeback_buffering_not_suck()` tries to close `/proc/sys/vm/dirty_background_bytes` after writing "0", python throws exception:
```
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 22] Invalid argument
```
This exception is not thrown when saving different numbers.

**Comment by iKarith** [comment]
Thanks @WaxyMocha, I'll be interested in knowing the more proper fix for this as well.

**Comment by WaxyMocha** [comment]
I appears that WoeUSB had the same issue ( slacka/WoeUSB#267 ), and their fix was to just remove this function. If being unresponsive during copying large files is no longer an issue, I may just do same thing.
