### ISSUE TITLE
Copying Files TO USB Faster Than USB Write Speeds Listed By Manufacter

### ISSUE THREAD

**Issue by TuckerEck** [WoeUSB/WoeUSB-ng#46]
## Issue Reproduce Instructions
Fresh Install Of Ubuntu 20.04.02 LTS Restart Open Terminal Update List And Upgrade Packages Restart Install WoeUSB-ng Format The USB In Disk to Fat32 Make Sure The USB Is not Mounted And Open WoeUSB Copy The 4.9GB Windows ISO To Flash Drive USING Fat32 Not NTFS Since ISO Is ONLY 4.9GB And The Install ESD

## Expected Behavior
> No error

## Current Behavior
> Copys files to USB Fasters than USB Speeds and then when i try running the USB from Boot Override IT List it But Stays in BIOS

### WoeUSB Source
> Downloaded using Python Pip3
> Installed from Ubuntu 20.04.02 Archive

### Information about the Operating System
Ubuntu 20.04.02 LTS With All Packages Up To Date

### Information about the Source Media
Windows 11 ISO Built Using UUPDump

### Information about the Target Device
SanDisk Cruzer Spark USB 2.0

**Comment by WaxyMocha** [comment]
I wouldn't worry about copying faster than what manufacturer said on the box, software will copy files as fast as it can. If I'm reading correctly, you successfully created usb stick with woeusb-ng but then it fails to boot? Can you say more about "But Stays in BIOS"?
