### ISSUE TITLE
WoeUSB-ng GUI Doesn't Launch

### ISSUE THREAD

**Issue by coltigore** [WoeUSB/WoeUSB-ng#49]
I've searched the issue tracker and is pretty sure that there's no duplicate issue already filed
 I've built the latest development snapshot using the instructions in README and verified that the issue can still be reproduced (for bug reports)

## Issue Reproduce Instructions
> 1. Launch WoeUSB from Apps list in GNOME
> 2. Enter Sudo password

## Expected Behavior
>Program Opens when launched

## Current Behavior
> WoeUSB will throw up the screen asking for privileges, then nothing happens
![image](https://user-images.githubusercontent.com/35747043/131172753-e28990e7-d37c-4b40-9d9e-c939d7963a9f.png)

### WoeUSB Source
> Installed using pip as the instructions showed for Fedora as well as building from source

### Information about the Operating System
> Fedora 34 Workstation running GNOME 40

**Comment by WaxyMocha** [comment]
Hi, have you tried running it twice?
Yes, this is serious question...

**Comment by coltigore** [comment]
@WaxyMocha I have, still no luck, on both the pip version and one I compiled :(

**Comment by WaxyMocha** [comment]
Gnome on some distributions appears to not work well with GUI's started as root. I don't have an solution for this outside of redesigning how GUI interfaces with core. For now you can try to use KDE or other, or just use terminal, there it should work well. 

#11

**Comment by Flashwalker** [comment]
pip installation not works:

```
$ sudo python3 -m pip install WoeUSB-ng
Collecting WoeUSB-ng
  Using cached WoeUSB_ng-0.2.12-py3-none-any.whl
Requirement already satisfied: termcolor in /usr/local/lib/python3.10/dist-packages (from WoeUSB-ng) (1.1.0)
Requirement already satisfied: wxPython in /usr/lib/python3/dist-packages (from WoeUSB-ng) (4.0.7)
Installing collected packages: WoeUSB-ng
Successfully installed WoeUSB-ng-0.2.12
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

```
$ woeusbgui
woeusbgui: command not found


$ ll /usr/local/bin/woeusbgui
ls: cannot access '/usr/local/bin/woeusbgui': No such file or directory
```

```
$ ll /usr/local/lib/python3.10/dist-packages/WoeUSB/
total 100
drwxr-xr-x 2 root root  4096 мар 30 14:14 data/
drwxr-xr-x 9 root root  4096 мар 30 14:14 locale/
drwxr-xr-x 2 root root  4096 мар 30 14:14 __pycache__/
-rwxr-xr-x 1 root root   900 мар 30 14:14 woeusb*
-rwxr-xr-x 1 root root  1249 мар 30 14:14 woeusbgui*
-rw-r--r-- 1 root root 28120 мар 30 14:14 core.py
-rw-r--r-- 1 root root 15977 мар 30 14:14 gui.py
-rw-r--r-- 1 root root   102 мар 30 14:14 __init__.py
-rw-r--r-- 1 root root  3007 мар 30 14:14 list_devices.py
-rw-r--r-- 1 root root   236 мар 30 14:14 miscellaneous.py
-rw-r--r-- 1 root root 15095 мар 30 14:14 utils.py
-rw-r--r-- 1 root root  4271 мар 30 14:14 workaround.py

```

How to fix this dumb shit:

```
sudo ln -s /usr/local/lib/python3.10/dist-packages/WoeUSB/woeusbgui /usr/local/bin/
```

**Comment by LulzT4T** [comment]
> pip installation not works:
> 
> ```
> $ sudo python3 -m pip install WoeUSB-ng
> Collecting WoeUSB-ng
>   Using cached WoeUSB_ng-0.2.12-py3-none-any.whl
> Requirement already satisfied: termcolor in /usr/local/lib/python3.10/dist-packages (from WoeUSB-ng) (1.1.0)
> Requirement already satisfied: wxPython in /usr/lib/python3/dist-packages (from WoeUSB-ng) (4.0.7)
> Installing collected packages: WoeUSB-ng
> Successfully installed WoeUSB-ng-0.2.12
> WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
> ```
> 
> ```
> $ woeusbgui
> woeusbgui: command not found
> 
> 
> $ ll /usr/local/bin/woeusbgui
> ls: cannot access '/usr/local/bin/woeusbgui': No such file or directory
> ```
> 
> ```
> $ ll /usr/local/lib/python3.10/dist-packages/WoeUSB/
> total 100
> drwxr-xr-x 2 root root  4096 мар 30 14:14 data/
> drwxr-xr-x 9 root root  4096 мар 30 14:14 locale/
> drwxr-xr-x 2 root root  4096 мар 30 14:14 __pycache__/
> -rwxr-xr-x 1 root root   900 мар 30 14:14 woeusb*
> -rwxr-xr-x 1 root root  1249 мар 30 14:14 woeusbgui*
> -rw-r--r-- 1 root root 28120 мар 30 14:14 core.py
> -rw-r--r-- 1 root root 15977 мар 30 14:14 gui.py
> -rw-r--r-- 1 root root   102 мар 30 14:14 __init__.py
> -rw-r--r-- 1 root root  3007 мар 30 14:14 list_devices.py
> -rw-r--r-- 1 root root   236 мар 30 14:14 miscellaneous.py
> -rw-r--r-- 1 root root 15095 мар 30 14:14 utils.py
> -rw-r--r-- 1 root root  4271 мар 30 14:14 workaround.py
> ```
> 
> How to fix this dumb shit:
> 
> ```
> sudo ln -s /usr/local/lib/python3.10/dist-packages/WoeUSB/woeusbgui /usr/local/bin/
> ```

So if it still doesnt work just 
   <     sudo woeusbgui  >
gui will launch in gnome

**Comment by abhishek-junghare** [comment]
> < sudo woeusbgui >

Yes, this works :+1:

```
sudo woeusbgui
```

**Comment by lemme-in-rn** [comment]
sorry, i'm a bit late to this, however when i try to use sudo woeusbgui it returns
```
Traceback (most recent call last):
  File "/usr/local/bin/woeusbgui", line 33, in <module>
    import WoeUSB.gui
ModuleNotFoundError: No module named 'WoeUSB'
```
am i just being stupid or?

**Comment by therapy** [comment]
> sorry, i'm a bit late to this, however when i try to use sudo woeusbgui it returns
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/bin/woeusbgui", line 33, in <module>
>     import WoeUSB.gui
> ModuleNotFoundError: No module named 'WoeUSB'
> ```
> 
> am i just being stupid or?


I had the same issue, for me it was a problem that the readme said to do `sudo pip3 install WoeUSB-ng` but since pip needs a venv, sudo didnt really work with that. I had to provide the pip and python3 binary manually.

```
sudo ~/code/python/.venv/bin/pip install WoeUSB-ng
cd /usr/local/bin
sudo ~/code/python/.venv/bin/python3 woeusbgui
```

 replace `~/code/python/.venv/bin/python3` with the path to your venv
