### ISSUE TITLE
grub-install or grub2-install command not found!

### ISSUE THREAD

**Issue by haidinhtran** [WoeUSB/WoeUSB-ng#50]
## Good Habit Checklist for Issue Reporting
Checkout [Mastering Markdown · GitHub Guides](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) if you needs help on the GitHub-flavored Markdown syntax.  You may remove sections and contents that don't apply.

* [x] I've searched the issue tracker and is pretty sure that there's no duplicate issue already filed
* [x] I've built the latest development snapshot using the instructions in README and verified that the issue can still be reproduced (for bug reports)

## Issue Reproduce Instructions
> 1. Launch WoeUSB by running `woeusbgui`
> 2. Do select Windows ISO file
> 3. Select Install

## Current Behavior
> WoeUSB errors with message "Installation Failed! Error: grub-install or grub2-install command not found!"

### WoeUSB Version
> Lastest using `sudo apt install git p7zip-full python3-pip python3-wxgtk4.0 ` then `sudo pip3 install WoeUSB-ng`

### WoeUSB Source
> https://github.com/WoeUSB/WoeUSB-ng

### Information about the Operating System
> Description:	Pop!_OS 21.04

### Information about the Source Media
> "Windows 10 X64 20H2 Pro OEM ESD MULTi-7 MARCH 2021 {Gen2}" downloaded from <https://1337x.to/torrent/4803921/Windows-10-X64-20H2-Pro-OEM-ESD-MULTi-7-MARCH-2021-Gen2/>

### Information about the Target Device
> USB Kingston DT100G3 16GB

**Comment by WaxyMocha** [comment]
Try `sudo apt install grub-pc`

**Comment by GainEager4141** [comment]
yep worked for me too

**Comment by cnsxxx09** [comment]
I had the same issue, albeit on Raspbian, and my search for a solution brought me here.
For me, albeit 3 years later and different OS, the solution didn't work as grub-pc is not available.
But this worked instead, hope it helps someone else in the future searching for the solution:

sudo apt install grub2-common
