### ISSUE TITLE
No shortcut on Applications menu (various Linux distros) but working using woeusbgui with terminal

### ISSUE THREAD

**Issue by DioEgizio** [WoeUSB/WoeUSB-ng#58]
* [*] I've searched the issue tracker and is pretty sure that there's no duplicate issue already filed

## Issue Reproduce Instructions
> 1. Install WoeUSB-ng on
> 2. No shortcut created in Applications menu

## Expected Behavior
> WoeUSB-ng shortcut in applications menu

## Current Behavior
> WoeUSB-ng has no shortcut 
Note:  /usr/share/applications/WoeUSB-ng.desktop seems to not exist

## Info of My Environment
WoeUSB Version:0.2.10

### Information about the Operating System
> Fedora Linux 35 (KDE Plasma spin)
> Debian Bookworm (testing) (KDE Plasma)

**Comment by PaPa1ya** [comment]
Same problem but on fedora 35 gnome

**Comment by frostmelody** [comment]
same thing on debian

**Comment by WaxyMocha** [comment]
what the hell happened

**Comment by DioEgizio** [comment]
I can confirm this issue happenes on Debian (testing) too

**Comment by fominator** [comment]
confirm om Ubuntu 20.04

**Comment by fominator** [comment]
confirm on Ubuntu 20.04

**Comment by bkdwt** [comment]
Can confirm on Fedora 35 wth Gnome.

**Comment by WaxyMocha** [comment]
I pushed update to pypi, if there are still problems please reopen the issue.
