### ISSUE TITLE
Gnome HIG compliant icon

### ISSUE THREAD

**Issue by ragnilorenzo** [WoeUSB/WoeUSB-ng#6]
Hi guys, this is the first issue I open on github so please apologize me if I made any mistake.
I just wanted to share my humble attempt to draw a Gnome HIG compliant icon ("compliant" at best, I'm not a pro designer in any way) for this awesome utility that saved me so much time and hassles.
I don't know if you like it or ever need it, but I'll be pleased if it can be any helpful!
Cheers, 
Lorenzo

PS. I'm open to suggestions and critics

<img src="https://user-images.githubusercontent.com/74972085/100109424-1c3c6d80-2e6c-11eb-934a-f4b167076115.png" width=50% height=50% />

<img src="https://user-images.githubusercontent.com/74972085/100109504-31b19780-2e6c-11eb-9922-12412591a268.png" />

**Comment by WaxyMocha** [comment]
I sure love your design, old logo still have win7 logo but we need to move with the times, right? :wink: 
But I don't have free time on my hands to handle it right now (maybe break during Christmas and new year?). I will definitely need to read how to handle copyright for an image. You will need to be ok with spirit of GPL.

**Comment by Lin-Buo-Ren** [comment]
Apart from the brand/mark reusing (USB/Windows) problem I like the design.

> I will definitely need to read how to handle copyright for an image. You will need to be ok with spirit of GPL.

As long as the image is available with a free software license(not necessarily GPL, there is no requirement that all assets in software must have the same license) it should be fine.

Also refer:

* [Non-Software Licenses | Choose a License](https://choosealicense.com/non-software/)
* [REUSE - Make licensing easy for everyone](https://reuse.software/)

**Comment by ragnilorenzo** [comment]
First of all thank you for your very kind feedback!
Licensing is a bit of a mess to say the least. I saw that Microsoft grants free permissions to use their windows logo only when you need it to demonstrate the full compatibility of your software with their OS, and yet you have to prove that "full compatibilty" while asking them the permission to use their logo, so doesn't seem a very viable way. This morning however I was wondering where is the boundary between a copyright infringement and an original work... for instance: the windows logo in my icon is partially covered by the thumb drive, plus is a bit different shape (it's slightly stretched to match the GNOME icon template) and has a colour taken from the GNOME palette, so although it's really similar to the original logo and fully recognisable as the windows logo, isn't technically their logo... shall we consider it a copyright infringement? What if, for example, we re-draw the windows logo in an even more simplified way (provided it is possible to design something even simpler ahah), or maybe changing some other details? Will it be again recognised as a plagiarism? 
Just thinking out loud guys because I'm really ignorant in that field and I'd love to hear your opinions...
One more idea: if I use in my draw a copyrighted logo designed by somebody else and distributed by him/her with an open licence (say for example CC), shall I refer to the licence of that very specific file or again I'll be in trouble with the original creator of the brand?

**Comment by Lin-Buo-Ren** [comment]
> I was wondering where is the boundary between a copyright infringement and an original work... for instance: the windows logo in my icon is partially covered by the thumb drive, plus is a bit different shape (it's slightly stretched to match the GNOME icon template) and has a colour taken from the GNOME palette, so although it's really similar to the original logo and fully recognisable as the windows logo, isn't technically their logo... shall we consider it a copyright infringement?

I'm not a lawyer, but I'd say that it still count as a copyright infringement if the copyright holder feels the same.  It does seem "fair" to use the Windows 10 logo to depict that this is a product relating to Microsoft Windows but it kinda in the gray area.

Can you add a bit of the reflection effect similar to the "window" like in [Window Vector SVG Icon (93) - SVG Repo](https://www.svgrepo.com/svg/168137/window)?  This modification should be enough to make the mark to be considered "not Windows 10 brand".

> if I use in my draw a copyrighted logo designed by somebody else and distributed by him/her with an open licence (say for example CC), shall I refer to the license of that very specific file or again I'll be in trouble with the original creator of the brand?

It depends on the original license's terms, if it's CC BY you'll be able to use it while complying with the attribution requirement (original authors' names and/or source), if it's CC BY-SA you'll have to license your work under the same CC BY-SA license as well.

**Comment by ragnilorenzo** [comment]
@Lin-Buo-Ren sorry for the delay in my response! 

> I'm not a lawyer, but I'd say that it still counts as a copyright infringement it is derived from the original brand by stretching&color changing. It does seem "fair" to use the Windows 10 logo to depict that this is a product relating to Microsoft Windows but it kinda in the gray area.

I see your point and totally agree with you. 

> Can you add a bit of the reflection effect similar to the "window" like in Window Vector SVG Icon (93) - SVG Repo? This modification should be enough to make the mark to be considered "not Windows 10 brand".

Yes, absolutely. I tried some things including the reflection effect you suggested but because of my scarce exeperience the result isn't really nice; I'll try a bit more in the next few days and I'll show what will eventually come out!

**Comment by ragnilorenzo** [comment]
Hi guys, I did some polishing work on the thumb drive itself, plus some tests on the windows logo which I rounded and made a bit 3-dimensional in first place and then coloured with different kind of gradients. 
Leaving out the fact that I'm still learning how to render a glossy effect in a non-80's fashion, I tried my best to emulate the "glass effect" @Lin-Buo-Ren suggested. The problem is that the more I move away from the flat gnome design, the more it looks a fish out of water... I think the better concepts are the ones more similar to the original windows logo design in terms of coloring, but again I don't know if those are suitable because of the risk of copyright infringement... Anyway let me know what you think ;) 

PS concept 2 does really need some color correction but with the "should-be-a-reflection-effect-gradient" is not that simple, if you like it I can work on it a bit more

**[concept 1]**

![woeusb0](https://user-images.githubusercontent.com/74972085/101757322-5007cc00-3ad7-11eb-918a-5e9cdea42a9d.png)

![WOEUSB_DESKTOP0](https://user-images.githubusercontent.com/74972085/101757340-55651680-3ad7-11eb-99f0-354ffc03f54f.png)

**[concept 2]**

![woeusb2](https://user-images.githubusercontent.com/74972085/101757548-90ffe080-3ad7-11eb-930c-5bbb081593a8.png)

![WOEUSB_DESKTOP2](https://user-images.githubusercontent.com/74972085/101760361-0a4d0280-3adb-11eb-9b5e-eef54b71b49f.png)

**[concept 3]**

![woeusb3](https://user-images.githubusercontent.com/74972085/101757616-a543dd80-3ad7-11eb-82ab-d165b15845f8.png)

![WOEUSB_DESKTOP3](https://user-images.githubusercontent.com/74972085/101757627-a8d76480-3ad7-11eb-9b5f-7ca1f573021b.png)

**Comment by WaxyMocha** [comment]
> There is a logo administration fee of US$3,500 for non-USB-IF members.

Huh. Anyways, sorry for lack of communication. End of university semester can be soul draining :). I have an idea, how would it look like without windows logo, usb stick at the center, with linux logo on it instead of USB's?

Like this: http://www.myiconfinder.com/icon/linux-bird-cmd-mat-cuts-penguin-tux-metro-ui-logo/10088

**Comment by Lin-Buo-Ren** [comment]
> [concept 2]

Apologies for the ignorance.  I'd like to have a quick note that I like this design.

> There is a logo administration fee of US$3,500 for non-USB-IF members.

This is another problem that we would like to deal with, here are my two opinions:

* Avoid it by dropping it
* Same as the Windows(R) logo problem, work around it with a similar but different concept design, e.g. devil fork/trident

> without windows logo, usb stick at the center, with linux logo on it instead of USB's

I am afraid that this may confuse users with applications that only make GNU/Linux bootable media.

---

I would like to apologize again for the poor communication over this issue, this shouldn't happen.  We appreciate your professional effort and kindness in helping WoeUSB/WoeUSB-ng better.

**Comment by WaxyMocha** [comment]
I also like concept 2 :).

 -  Avoid it by dropping it

Right, how it would look like without USB logo?

I would also like to apologize for the poor communication.

**Comment by Lin-Buo-Ren** [comment]
> [concept 1]

On second thought I found I appreciate the aesthetics of this design and have an idea of putting the "Tux" character(attribution: [lewing@isc.tamu.edu Larry Ewing](mailto:lewing@isc.tamu.edu) and [The GIMP](https://en.wikipedia.org/wiki/GIMP)) on the other side of the "window", somewhat like this (except that Tux is on the other side of the window, looking at the huge USB stick inside the "room" through the "window".)

![concept pic](https://user-images.githubusercontent.com/13408130/107153009-3800db80-69a6-11eb-833d-f48b2699a2c6.png)

**Comment by WaxyMocha** [comment]
Like this?
Taken from [here](https://imgur.com/gallery/7UCGj)

![52MQ0Vr](https://i.imgur.com/52MQ0Vr.jpg)

**Comment by Lin-Buo-Ren** [comment]
> Like this?

Exactly.

**Comment by ragnilorenzo** [comment]
Hi guys! Don't worry, everybody has its own busy life to keep up with, I totally understand :) 
Nice to hear from you again! 

> without windows logo, usb stick at the center, with linux logo on it instead of USB's

Yeah probably it's the more sensible design and I also thought about it, but I agree with @Lin-Buo-Ren: there's already a bunch of linux applications that use a very similar design and especially on small displays it's gonna be undistinguishable from those others...

> On second thought I found I appreciate the aesthetics of this design and have an idea of putting the "Tux" character(attribution: lewing@isc.tamu.edu Larry Ewing and The GIMP) on the other side of the "window"

> I also like concept 2 :).
Right, how it would look like without USB logo?



I'm glad you liked my concepts and I did some more testing I want to show you


![woeusb4](https://user-images.githubusercontent.com/74972085/107353012-d5eec600-6acc-11eb-97a1-5c638f83a5a2.png)


![woeusb5](https://user-images.githubusercontent.com/74972085/107353045-df782e00-6acc-11eb-8fcf-60b91872d2a9.png)


I did those really fast so they need some more polishing, I just wanted to show you some more solutions. 
Of course every element from any draw I sent is interchangeable so let me know if you have any request. 
One last note: the woeusb text inside the key is more of a placeholder, I still need to find something that doesn't make the thumb drive too much empty...

**Comment by Lin-Buo-Ren** [comment]
> I'm glad you liked my concepts and I did some more testing I want to show you

I found the second option preferable, as it makes the Linux reference subtle but visible so that the user won't misinterpret that the application support Linux bootable media preparation as well.

> One last note: the woeusb text inside the key is more of a placeholder, I still need to find something that doesn't make the thumb drive too much empty...

I actually like the current design and would like to stick to it, as long as there's no obvious alternative, of course.

**Comment by ragnilorenzo** [comment]
> I found the second option preferable, as it makes the Linux reference subtle but visible

I totally agree; plus i think that from an aestethic point of view it looks more consistent.

> Tux is on the other side of the "window", looking at the huge USB stick inside the "room" through the "window"

I'm sorry I forgot about that while making the last two concepts, I only realized by rereading!

![woeusb_new1](https://user-images.githubusercontent.com/74972085/108184994-1a511600-710c-11eb-9cb2-2f0b5fa2592c.png)

![woeusb_new2](https://user-images.githubusercontent.com/74972085/108185015-21782400-710c-11eb-95d5-e91450c6c3fe.png)

The difficult thing here is to make the penguin not look sitting while making sure not to cut its snout too much...

**Comment by Lin-Buo-Ren** [comment]
The second one is preferable

For legal reasons, I would like to require that all assets that you've used in this work (USB pen drive, the "window", the Tux) are either:

* Your own work
* Public assets with free licenses, known authorship, and source
* Considered fair-use in the aforementioned discussions

**Comment by ragnilorenzo** [comment]
> The second one is preferable.

I agree. 

Regarding the licesing: 

- the usb drive is completely my own work
- the original window path was taken from [there](https://en.m.wikipedia.org/wiki/File:Windows_logo_-_2012.svg) and then reworked
- the tux is from [there](https://en.wikipedia.org/wiki/Tux_(mascot)#/media/File:TuxFlat.svg) and then also reworked

PS I just noticed that in the previous post the window had "lost" its shadow... edited :)

**Comment by WaxyMocha** [comment]
- Your work
- "This logo image consists only of simple geometric shapes or text. It does not meet the threshold of originality needed for copyright protection, and is therefore in the public domain."
- GPL

So I would say that from licensing point of view we are fine.

**Comment by ragnilorenzo** [comment]
Yes I think so! 

> "This logo image consists only of simple geometric shapes or text. It does not meet the threshold of originality needed for copyright protection, and is therefore in the public domain."

That got me thinking if this being the case we can use this usb logo as well https://commons.wikimedia.org/wiki/File:USB_icon.svg 

What do you think?

**Comment by WaxyMocha** [comment]
Oh, so the fork is not a USB IF logo, you can see thier logos here https://www.usb.org/sites/default/files/usb-if_logo_usage_guidelines_final_103019.pdf. If this is the case then... I think we can.

**Comment by Lin-Buo-Ren** [comment]
I believe that the trident logo is unnecessary as the pen drive is clearly a USB device.

**Comment by Lin-Buo-Ren** [comment]
> "This logo image consists only of simple geometric shapes or text. It does not meet the threshold of originality needed for copyright protection, and is therefore in the public domain."

"This work includes material that may be protected as a trademark in some jurisdictions. If you want to use it, you have to ensure that you have the legal right to do so and that you do not infringe any trademark rights."

Also: 

* [Microsoft Trademark & Brand Guidelines | Trademarks](https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/general)
* [Publications, Seminars, & Conference Guidelines | Trademarks](https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/publications.aspx)

```
"*You may** use Microsoft trademarks in text solely to refer to and/or link to Microsoft’s products and services and in accordance with the terms of these Guidelines."
```

```
These Publications, Seminars, and Conferences Guidelines allow you to use Microsoft word-only [Trademarks](https://www.microsoft.com/trademarks) (the “Marks”) in the title of publications, seminars, and conferences solely in accordance with the terms of these guidelines.
 ```

 ```
**You may** use the Marks in the title of publications, seminars, and conferences provided:

- the Marks are directly related to a specific Microsoft product or service that is referenced in the publication, seminar, or conference;
```

We'll have to assume it is a fair use of the trademark as:

* This product is related to a Microsft product(Windows) and is rightfully appear to be so.
* This product(making Windows installation media under GNU/Linux easier) should, to a reasonable extent), not interfere with Microsoft's interests.
* The design is intentionally redirected to use the "window" concept, instead of the "Microsoft Windows logo"

**Comment by Lin-Buo-Ren** [comment]
@ragnilorenzo

> Regarding the licesing:
> 
>     * the usb drive is completely my own work
> 
>     * the original window path was taken from [there](https://en.m.wikipedia.org/wiki/File:Windows_logo_-_2012.svg) and then reworked
> 
>     * the tux is from [there](https://en.wikipedia.org/wiki/Tux_(mascot)#/media/File:TuxFlat.svg) and then also reworked

Great.  Due to licensing requirement of the Tux image(GPLv2+), we are required to include the source design document(i.e. Pixelmator Pro, according to the image metadata) along with the product, is that acceptable to you?  Using other images with a permissive license will lift this requirement, of course.

**Comment by ragnilorenzo** [comment]
> "This work includes material that may be protected as a trademark in some jurisdictions. If you want to use it, you have to ensure that you have the legal right to do so and that you do not infringe any trademark rights."

I see, It did seem too good to be true to be able use any image only because the original creator wasn't the owner of the trademark... nevermind, I agree that the usb stick is pretty recogniseable.

> Due to licensing requirement of the Tux image(GPLv2+), we are required to include the source design document

Sure! 

> publish it with a compatible license

Beside declaring that the image is given with a certain license (which as I understand is made by adding a license text file to the image repo), do I have to do something else in order to make the licence "effective"? 

Moreover - please excuse my ignorance regarding how github works but as I said that is my first contribution ever -, since I see that woeusb itself is gplv3 licensed, will just merging the icon and its source file to the repo give those the same license as the repo itself? (so gpl3 for instance)

**Comment by WaxyMocha** [comment]
Here is very short summary of gpl
https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)

From what I understand, all you need to do is to say that you are giving it with gplv3 license, then I can just throw it into repository, but if you would do it as gplv2 or mit then I would need to say that this logo is under different license. 

It is not about textfile on github, file with license just tells other people about conditions of using and modifying the software.

If you would place your work in repository on your profile and not include license, I can't use it. I would need to contact you and ask if I can use it and under what conditions.

**Comment by Lin-Buo-Ren** [comment]
Apologies for the ignorance.

To avoid confusion I would like to note that, WoeUSB is now a multi-product project, which currently includes:

* WoeUSB  
  The original implementation based on Bash, currently maintained by me
* WoeUSB-frontend-wxgtk  
  The original graphical application, based on WxWidget
* WoeUSB-ng 
  The Python rework, by @WaxyMocha

As the contribution request is made here I would like to ask that whether you would be fine to contribute this icon to the WoeUSB project as a whole(a.k.a. can be used by all derived products), or specifically to WoeUSB-ng?  Either option is acceptable.

> Beside declaring that the image is given with a certain license (which as I understand is made by adding a license text file to the image repo), do I have to do something else in order to make the licence "effective"?

Any form of a declaration should be sufficient to make the license effective, however, doing it well is always helpful nonetheless.
 Here is the requirements:

Commit the file with the following commit message:

```
SPDX-License-Identifier: GPL-3.0-or-later
Signed-off-by: _copyright_holder_name_ <_copyright_holder_contact_>
```

The `SPDX-License-Identifier` tag specifies the license of the commit([SPDX License List | Software Package Data Exchange (SPDX)](https://spdx.org/licenses/)).  The `Signed-off-by` field specifies compliance of [Developer Certificate of Origin](https://developercertificate.org/).

Create the pull request on either of the following repositories, according to your preference of the aforementioned inquiry:

* [WoeUSB/branding: Assets that identify and promote WoeUSB and its products.](https://github.com/WoeUSB/branding)
* [WoeUSB/WoeUSB-ng: WoeUSB-ng is a simple tool that enable you to create your own usb stick windows installer from an iso image or a real DVD. This is a rewrite of original WoeUSB.](https://github.com/WoeUSB/WoeUSB-ng)

we can handle other details (file naming, location, and other details) later ourselves.

**Comment by ragnilorenzo** [comment]
Please forgive my absence!

> all you need to do is to say that you are giving it with gplv3 license, then I can just throw it into repository, but if you would do it as gplv2 or mit then I would need to say that this logo is under different license.

Since this is a collaborative project - and you were so kind to allow me to contribute - I personally see no point in using a different license. I give you full rights on my own work and so, if you want, you can include it into the projects repo under gplv3 which is totally fine to me. 

@Lin-Buo-Ren Thank you very much for the detailed explanation! 

> I would like to ask that whether you would be fine to contribute this icon to the WoeUSB project as a whole(a.k.a. can be used by all derived products), or specifically to WoeUSB-ng

I would be happy to contribute to the project as a whole. If you like the icon feel free to use it for whatever you need it for any of the products listed above.

> Commit the file with the following commit message (...) Create the pull request on either of the following repositories

Okay, I'll prepare the files and create a pull request as soon as possible!

**Comment by ragnilorenzo** [comment]
Sorry for the delay!

I didn't provide the svgs in first place because of some odd export problem with pixelmator (I'd be better off using inkscape from the beginning... lesson learned ;) ) Anyway I finally managed to make some polished files that I'll be uploading this evening. I also took the opportunity to make some other minor adjustments.

I chose the /branding repo because I thought it would be a consistent choice for the icon. Please let me know if the pull request is made correctly; I noticed the "empty file" error immediately after uploading but then I figured out that clicking on rich difs did the trick so I ignored it...
