### ISSUE TITLE
packaging: woeusb-ng

### ISSUE THREAD

**Issue by Stunkymonkey** [WoeUSB/WoeUSB-ng#63]
I am currently packaging this repo for nixpkgs, which is used by NixOS.
My current progress can be seen here: https://github.com/NixOS/nixpkgs/pull/149382
Currently I managed to get the cli-tool working. The gui does not work currently, due to the polkit-actions needed, which are a bit tricky on NixOS.

This repo contains binaries `woeusb` and `woeusbgui `.
My main question is:
Should both of them be shipped in a single package, or do you prefer them to be split up?

**Comment by WaxyMocha** [comment]
Hi, 
cli was built in a way to allow it to work independent from gui, and I think that it should be in independent package

**Comment by Stunkymonkey** [comment]
thanks for the fast response.

**Comment by Stunkymonkey** [comment]
@WaxyMocha another question:
should we replace `woeusb` with `woeusb-ng`?

**Comment by WaxyMocha** [comment]
I think it should be `woeusb`, it's easier for user and there is no point of having both versions installed

**Comment by brlin-tw** [comment]
> I think it should be `woeusb`, it's easier for user and there is no point of having both versions installed

This will conflict with the `woeusb` command in the original bash implementation, though.  A conflict relationship must be in place between the two package if we go in that direction.

**Comment by WaxyMocha** [comment]
My package on Arch is doing it ¯\_(ツ)_/¯
```
conflicts=(
    'woeusb'
    'woeusb-git'
)
```
