### ISSUE TITLE
Possible data loss if close warning window with X

### ISSUE THREAD

**Issue by severgun** [WoeUSB/WoeUSB-ng#81]
## Describe the bug ##

If you press X(cross) to close warning window, it will proceed installation process. Could lead to unintentional data loss.
Also seems like "Yes" button pre-selected.

## To Reproduce ##

1. Select ISO
2. Select drive
3. Press Install
4. Close warning window with X

## Expected behavior ##

Process cancellation

## Environment ##

- OS: Kubuntu 22.04
- WoeUSB-ng: 0.2.10-2

**Comment by mk-pmb** [comment]
Would you mind checking what happens when users press the Escape key instead? I'm not 100% sure which X you meant, and neither what kinds of data loss could occurr if I try.

**Comment by severgun** [comment]
❌ - regular button to close window.

What kind of data loss? It will proceed process and format flash drive.
