### ISSUE TITLE
Add faulty dependencies to the README

### ISSUE THREAD

**Issue by EchedeyLR** [WoeUSB/WoeUSB-ng#82]
While running in a default GNU/Linux system you could run into issues and WoeUSB won't run because of faulty non-referenced dependencies.

I list here dependencies for the average Debian-based OS:
- `parted`: making partitions (I don't know why using the command and not the `python3-parted` module which uses `libparted` being more secure for surface attack and performant).
- `dosfstools`: formatting partitions to FAT.
- `ntfs-3g`: formatting partitions to NTFS.

**Comment by deisi** [comment]
I experienced the same issue. Using woeUSB under Ubuntu 22.04 installing it according to the readme gave me the error message:
```mkntfs not found```

After installing `ntfs-3g` think started to work.
