### ISSUE TITLE
Failed to mount target volume

### ISSUE THREAD

**Issue by scottmeup** [WoeUSB/WoeUSB-ng#83]
## Issue Reproduce Instructions
 1. Launch WoeUSB by running `woeusbgui`
 2. Select source, target, click install

## Expected Behavior
No error / woeusb prepares USB drive

## Current Behavior
WoeUSB errors with message

/dev/sdb: 2 bytes were erased at offset 0x000001fe (dos): 55 aa
/dev/sdb: calling ioctl to re-read partition table: Success
/dev/sdb1 is mounted.
Refusing to make a filesystem here!
Mount is denied because the NTFS volume is already exclusively opened.
The volume may be already mounted, or another software may use it which
could be identified for example by the help of the 'fuser' command.

### WoeUSB Version 
WoeUSB 0.2.10

### WoeUSB Source
http://aur.archlinux.org/packages/woeusb-ng

### Information about the Operating System
> Different OS distributions provides different characteristics and may influence the result of running WoeUSB.  Run `lsb_release --description` or `lsb_release -d` in a terminal to acquire this information.
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        21.3.6
Codename:       Ruah

### Information about the Source Media
Windows 11 Downloaded from Microsoft

### Information about the Target Device
Kingston Traveller 3.0 64gb

I found this issue which gave a solution by running woeusbgui from terminal and googling the error. 
If I read the issue listed below correctly, something was planned to be implemented.
Would it be possible to have something rgarding the error in a readme or a text prompt for noob users?
The cause of the error message provided by the gui was not clear to me.
https://github.com/slacka/WoeUSB/issues/238

**Comment by JonnyTech** [comment]
Please unmount the target volume first: `sudo umount /dev/sdb1`

**Comment by scottmeup** [comment]
The volume is unmounted first. 

From the issue listed here it seems that automounting the volume is the cause of the problem 

https://github.com/slacka/WoeUSB/issues/238

**Comment by JonnyTech** [comment]
Great that you found the problem is an external OS setting. Please close this issue.

**Comment by scottmeup** [comment]
Yes, thank you. It is great. 

I though some helpful text in either the readme or the program's error dialog might be helpful for new users.

I'll close the issue.

**Comment by janberkucar** [comment]
TR

> Yes, thank you. It is great.
> 
> I though some helpful text in either the readme or the program's error dialog might be helpful for new users.
> 
> I'll close the issue.

The issue link provided is down.

**Comment by ffelipeoliveira** [comment]
> The issue link provided is down.

Checked the link on internet archive and found out that there's a option for automounting storage drivers under system settings -> removable devices. Uncheck "On conection". Words may be different depending on the version but it's probably something like this.
