### ISSUE TITLE
Policy was updated, please run this program again

### ISSUE THREAD

**Issue by RonAndDumbleTheCats** [WoeUSB/WoeUSB-ng#86]
## Good Habit Checklist for Issue Reporting
Checkout [Mastering Markdown · GitHub Guides](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) if you needs help on the GitHub-flavored Markdown syntax.  You may remove sections and contents that don't apply.

* [x] I've searched the issue tracker and is pretty sure that there's no duplicate issue already filed
* [x] I've built the latest development snapshot using the instructions in README and verified that the issue can still be reproduced (for bug reports)

## Issue Reproduce Instructions
> 1. Launch WoeUSB by running woeusbgui

## Expected Behavior
> No error

## Current Behavior
> WoeUSB errors with message Policy was updated, please run this program again

### WoeUSB Version0 .2.10-2

> For source code build, run `git describe --tags --always --dirty` under the source tree, for prebuilt releases refer the source that provides WoeUSB

### WoeUSB Source

> Installed from pip on

### Information about the Operating System
> Different OS distributions provides different characteristics and may influence the result of running WoeUSB.  Run `lsb_release --description` or `lsb_release -d` in a terminal to acquire this information.

### Information about the Source Media
> "Windows 11 MULTI" downloaded from <https://microsoft.com/download/windows-11>

### Information about the Target Device
> GIGASTONE 16GB USB-2.0

**Comment by JonnyTech** [comment]
Please provide all of the requested information, especially:

> Information about the Operating System
> Different OS distributions provides different characteristics and may influence the result of running WoeUSB.
> Run `lsb_release --description` or `lsb_release -d` in a terminal to acquire this information.

**Comment by HenriqueMiossi** [comment]
Try running it as root, the same problem happened to me (I'm using Fedora 36) when running via GUI or without privileges, but it worked doing this way. My guess is that this policy updater for some reason did not work. Maybe because I'm using Fedora?
