### ISSUE TITLE
AUR package `woeusb-ng` has no maintainer

### ISSUE THREAD

**Issue by lazytownfan** [WoeUSB/WoeUSB-ng#98]
## Good Habit Checklist for Issue Reporting
Checkout [Mastering Markdown · GitHub Guides](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) if you needs help on the GitHub-flavored Markdown syntax.  You may remove sections and contents that don't apply.

* [X] I've searched the issue tracker and is pretty sure that there's no duplicate issue already filed

## Issue Reproduce Instructions
1. Go to the [`woeusb-ng`](https://aur.archlinux.org/packages/woeusb-ng) AUR package
2. Examine the "Maintainer" line.

## Expected Behavior
There should be a maintainer.

## Current Behavior
There is currently no maintainer, since the package was [reported](https://aur.archlinux.org/pkgbase/woeusb-ng/flag-comment) as out-of-date on March 8, 2023.

### WoeUSB Version
0.2.10-1
### WoeUSB Source
`woeusb-ng` from the AUR

### Information about the Operating System
Manjaro Linux, Unstable branch

**Comment by basil-squared** [comment]
there appears to be a maintainer.

**Comment by lazytownfan** [comment]
Thanks for letting me know!
