### ISSUE TITLE
make this simpler for people to use who are not linux savey

### ISSUE THREAD

**Issue by madmaxgrey** [WoeUSB/WoeUSB-ng#99]
create a appimage of woeusb-ng as a simple means of usage just download and run it
i came across so many people who don't know how to read instructions or follow instructions just make a appimage for those 
who are software irritate

sorry this is not following the given post layout you provide to follow but this needs to be made for people who cant follow long instructions

**Comment by martin-kokos** [comment]
I think progressing with this PR https://github.com/WoeUSB/WoeUSB-ng/pull/79 is a step towards making an AppImage easily.

**Comment by basil-squared** [comment]
Hello! WoeUSB-ng can be installed first by installing python, which can be done using your package manager. afterwards, you should be able to install it by running pip3 install woeusb-ng. after that has finished, run it using sudo woeusbgui.
